### ISSUE TITLE
Some questions about the experimental details.

### ISSUE THREAD

**Issue by JXH-SHU** [haochen-rye/NeRV#13]
This is an impressive job. I try to reproduce the results in the paper. I found that there are two parameters that control the compression ratio, quantization (bit length) and pruning ratio. I was wondering how did you get the curves for the BDBR? Looking forward to your reply.

**Comment by haochen-rye** [comment]
If your mean bitrates-distortion figures (Fig. 7 and Fig. 8), we simply try different combinations (grid search etc.) and get many (bpp, PSNR) pairs, and then plot them in all in one figure and choose the best setup (quantization bits/axis, pruning ratio).
Since pruning and quantization should be pretty fast to run and try.

**Comment by lgupta-mle** [comment]
@haochen-rye What kind of different combinations did you try? I am trying to obtain an RD-curve for your codec with my dataset.
