### ISSUE TITLE
Dumped images with different resolution.

### ISSUE THREAD

**Issue by QLaHPD** [haochen-rye/NeRV#9]
The images produced by the network have a different (lower) resolution than the original, which argument controls this?

PS: Also, the output images have a much worse PSNR than during training. Train ~28; Test ~10

**Comment by haochen-rye** [comment]
Given one sample command:
```
python train_nerv.py -e 300   --lower-width 96 --num-blocks 1 --dataset bunny --frame_gap 1 \
    --outf bunny_ab --embed 1.25_40 --stem_dim_num 512_1  --reduction 2  --fc_hw_dim 9_16_26 --expansion 1  \
    --single_res --loss Fusion6   --warmup 0.2 --lr_type cosine  --strides 5 2 2 2 2  --conv_type conv \
    -b 1  --lr 0.0005 --norm none --act swish 
```
`fc_hw_dim 9_16_26`  define the FC feature map size (9*16 here),  ` --strides 5 2 2 2 2` specify the upsampling factor for each stage, therefore the final resolution is` (9*5*2*2*2*2, 16*5*2*2*2*2) = ( 720, 1280)`

Training PSNR should be very close to testing PSNR since we are tasing  and testing datasets are the same, you may check if your evaluate code follows the same way as your training.
